@startuml

header
Einige Anwendungsfälle
endheader

(Anwendungsfall Vier)

:Akteur Eins: -> (Anwendungsfall Eins)
:Akteur Zwei: --> (Anwendungsfall Zwei)
:Akteur Drei: ---> (Anwendungsfall Drei)
:Akteur Vier:
actor Akteur

footer Beispiele der Anwendungsfälle

@enduml
