@startuml

header
Einige Anwendungsfälle
endheader

(Anwendungsfall Eins)
(Anwendungsfall Zwei)
(Anwendungsfall Drei)
(Anwendungsfall Vier)

:Akteur Eins:
:Akteur Zwei:
:Akteur Drei:
:Akteur Vier:
actor Akteur

footer Beispiele der Anwendungsfälle

@enduml
